services:
  - type: web
    name: dama-bet-backend
    runtime: node
    repo: https://github.com/santwoxx/dama-bet-teste
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/stats
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://dama-bet.vercel.app
